name: Generate IonStack Config

"on":
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pyelftools
        run: |
          python -m pip install --upgrade pip
          pip install pyelftools

      - name: Check generator
        run: |
          python -m py_compile gen_ionstack_config.py
